server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Rootroot@1045
    username: root
    url: jdbc:mysql://localhost:3306/auth2

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
      show-sql: true

  mail:
    host: localhost
